services:
  fasten:
    image: ghcr.io/fastenhealth/fasten-onprem:main
    hostname: fasten
    ports:
      - "9090:8080"
    volumes:
      - /opt/fasten/db:/opt/fasten/db
      - /opt/fasten/cache:/opt/fasten/cache
      - /opt/fasten/certs:/opt/fasten/certs/shared
